//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaijinSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int id { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdCourse { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
    
        public virtual UserDB UserDB { get; set; }
        public virtual Courses Courses { get; set; }
    }
}
