//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaijinSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> Mark { get; set; }
    
        public virtual UserDB UserDB { get; set; }
        public virtual Courses Courses { get; set; }
    }
}
