//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaijinSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleMaterial
    {
        public int id { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public string MaterialURL { get; set; }
        public string Description { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
